
export const
    USER_LOGIN_SUCCESS : string = "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL_USER_NOT_REGISTERED : string = "USER_LOGIN_FAIL_USER_NOT_REGISTERED",
    USER_LOGIN_FAIL_USER_NOT_VERIFIED : string = "USER_LOGIN_FAIL_USER_NOT_VERIFIED",
    USER_LOGIN_FAIL_USER_INVALID_PASSWORD : string = "USER_LOGIN_FAIL_USER_INVALID_PASSWORD",
    NEW_USER_REGISTRATION_SUCCESS : string = "NEW_USER_REGISTRATION_SUCCESS",
    NEW_USER_REGISTRATION_FAIL_USER_EXISTS : string = "NEW_USER_REGISTRATION_FAIL_USER_EXISTS",
    NEW_USER_REGISTRATION_FAIL_INVALID_EMAIL_ID : string = "NEW_USER_REGISTRATION_FAIL_INVALID_EMAIL_ID",
    EMAIL_VERIFY_SUCCESS : string = "EMAIL_VERIFY_SUCCESS",
    EMAIL_VERIFY_FAIL_INVALID_TOKEN : string = "EMAIL_VERIFY_FAIL_INVALID_TOKEN",
    EMAIL_VERIFY_FAIL_EXPIRED_TOKEN : string = "EMAIL_VERIFY_FAIL_EXPIRED_TOKEN",
    EMAIL_VERIFY_FAIL_INVALID_REQUEST : string = "EMAIL_VERIFY_FAIL_INVALID_REQUEST",
    EMAIL_VERIFY_FAIL_MALFORMED_TOKEN : string = "EMAIL_VERIFY_FAIL_MALFORMED_TOKEN",
    EMAIL_VERIFY_FAIL_PROCESS_ERROR : string = "EMAIL_VERIFY_FAIL_PROCESS_ERROR",
    EMAIL_VERIFY_REGENERATE_SUCCESS : string = "EMAIL_VERIFY_REGENERATE_SUCCESS",
    EMAIL_VERIFY_REGENERATE_FAIL_INVALID_REQUEST : string = "EMAIL_VERIFY_REGENERATE_FAIL_INVALID_REQUEST",
    EMAIL_VERIFY_REGENERATE_FAIL_PROCESS_ERROR : string = "EMAIL_VERIFY_REGENERATE_FAIL_PROCESS_ERROR"
;
